apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../auth/poc-htpasswd
  - ../../storage/sno-local
  - ../../workload
components:
  - ../../components/agentic-runner
images:
  - name: podpilot
    newName: image-registry.openshift-image-registry.svc:5000/ai-ops/podpilot
    newTag: latest
  - name: podpilot-oc-runner
    newName: image-registry.openshift-image-registry.svc:5000/ai-ops/podpilot-oc-runner
    newTag: latest
patches:
  - path: pod-security-context.yaml
  - path: storage-class-patch.yaml
  - path: runtime-config-patch.yaml
